// Turns scripts/icons/*.svg (Tabler outline) into src/icons.tsx: one React component per file,
// background rect stripped, currentColor, 1em. Run: node scripts/gen-icons.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
const dir = new URL('./icons/', import.meta.url)
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const pascal = (s) => camel(s).replace(/^[a-z]/, (c) => c.toUpperCase())
let out = `// Generated by scripts/gen-icons.mjs from Tabler Icons (MIT). Do not edit by hand.
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string }

function Icon({ size = '1em', children, ...rest }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false" {...rest}>
      {children}
    </svg>
  )
}
`
for (const f of readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(new URL(f, dir), 'utf8')
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '')
    .replace(/(stroke|fill|clip)-(width|linecap|linejoin|rule|dasharray)=/g, (_, a, b) => `${a}${b[0].toUpperCase()}${b.slice(1)}=`)
    .trim()
    .split('\n').map((l) => l.trim()).filter(Boolean).join('')
  const name = 'Icon' + pascal(f.replace('.svg', ''))
  out += `\nexport const ${name} = (p: IconProps) => <Icon {...p}>${inner}</Icon>\n`
}
writeFileSync(new URL('../src/icons.tsx', import.meta.url), out)
console.log('wrote src/icons.tsx')
