skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crumb_clicker = "G86X3J8uUmYfaZawC2FDAjgVNMfyRgpUjyLQNQGxYfTR"
crumb_emission = "C8NRjLU9ajS5okBSbDhMBXsF2naVGm82y6g3hdefTQcY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
